#!/usr/bin/env bash
# Writes ios/.xcode.env.local so Xcode script phases use the same Node as .nvmrc (20 LTS).
# Node 24 at /usr/local/bin/node breaks React Native Codegen (ERR_INVALID_PACKAGE_CONFIG).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IOS_ENV_LOCAL="$ROOT/ios/.xcode.env.local"

unset npm_config_prefix NPM_CONFIG_PREFIX 2>/dev/null || true
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [[ -s "$NVM_DIR/nvm.sh" ]]; then
  # shellcheck disable=SC1091
  source "$NVM_DIR/nvm.sh"
  if [[ -f "$ROOT/.nvmrc" ]]; then
    nvm install >/dev/null 2>&1 || true
    nvm use >/dev/null
  fi
fi

NODE="$(command -v node)"
if [[ -z "$NODE" ]]; then
  echo "[crea-app] No node binary found. Install Node 20 (see .nvmrc)." >&2
  exit 1
fi

MAJOR="$(node -p "process.version.slice(1).split('.')[0]")"
if [[ "$MAJOR" -ge 24 || "$MAJOR" -lt 18 ]]; then
  echo "[crea-app] Node $(node -v) is unsupported for Expo 52. Use Node 20 LTS (nvm use)." >&2
  exit 1
fi

cat >"$IOS_ENV_LOCAL" <<EOF
# Auto-generated by scripts/sync-xcode-node.sh — do not commit (gitignored).
# Xcode ReactCodegen / bundle scripts must use Node 20, not /usr/local/bin/node (v24).
export NODE_BINARY=$NODE
EOF

echo "[crea-app] ios/.xcode.env.local → Node $(node -v) at $NODE"
